### PR TITLE
Add Mesos dashboards

### PR DESCRIPTION
**Pull request by jwy**
Mesos Clusters, Mesos Cluster, Mesos Master, and Mesos Slave dashboards.

### CODE REVIEW

**Comment by beccatortell** [comment]
Ram, please run your script on these

**Comment by ramjothikumar** [comment]
@beccatortell ran script and squashed my change into the above commit.

**Comment by jwy** [comment]
Hm, the sf_discoveryQuery values I exported don't look correct. They're values I previously had in there. Please hold off on merging while I investigate.

**Comment by jwy** [comment]
Never mind, the sf_discoveryQuery values I was looking at will be ignored. We are good to go.

**Pull request merged**
